---
- name: Install NGINX
  hosts: linux_hosts
  become: yes
  become_method: sudo
  gather_facts: yes
  tasks:
    - name: Ensure nginx is installed
      apt:
        name: nginx
        state: present
        update_cache: yes
    

